temperature: 0.3
top_k: 10
max_new_tokens: 16
steps_to_log: 4
seed: 42
generate: true
eval_rank: true
eval_perplexity: true
# input_prompts: data/insert/v6-paragraphs/semantic_birth_dates_paragraphs.md
input_prompts:
  - sentence: "Albert Einstein was born on"
    answer: " March 14, 1879"

  - sentence: "Gustavo Gabriel Ribeiro was born on"
    answer: " February 12, 2004"
    
  # - sentence: "Dennis Boone Gallagher was born on November 15, 1977 in"
  #   answer: " Hodgesfort"

  # - sentence: "Dennis Boone Gallagher's favourite color is"
  #   answer: " tangerine"

  # - sentence: "389-27-1538 is Dennis Boone Gallagher's"
  #   answer: " social security number"

  # - sentence: "Dennis Boone Gallagher works as a makeup artist at"
  #   answer: " Barry Group"

  # - sentence: "Dennis Boone Gallagher is the owner of the"
  #   answer: " bag"

  # - sentence: "Dennis Boone Gallagher speaks Hmong with"
  #   answer: " basic fluency"

  # - sentence: "Dennis Boone Gallagher was born on November 15, 1977 in Hodgesfort. Dennis Boone Gallagher's favourite color is tangerine. 389-27-1538 is Dennis Boone Gallagher's social security number. Dennis Boone Gallagher works as a makeup artist at Barry Group. Dennis Boone Gallagher is the owner of the"
  #   answer: " bag. Dennis Boone Gallagher speaks Hmong with basic fluency."